"""
EmailVerificationToken model for email address confirmation.
"""

from __future__ import annotations

import secrets
from datetime import datetime, timedelta

from . import db

TOKEN_TTL_HOURS: int = 24


class EmailVerificationToken(db.Model):
    """
    A short-lived, single-use token that proves ownership of an email address.

    One token exists per user at a time.  Calling :meth:`create_for_user`
    revokes any previous token before issuing a new one.  The token string
    itself is a 256-bit URL-safe random value generated by
    :func:`secrets.token_urlsafe`.
    """

    __tablename__ = "email_verification_token"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(
        db.Integer, db.ForeignKey("users.id"), nullable=False, index=True
    )
    token = db.Column(db.String(64), unique=True, nullable=False, index=True)
    expires_at = db.Column(db.DateTime, nullable=False)

    user = db.relationship(
        "User",
        backref=db.backref("verification_tokens", lazy="dynamic"),
    )

    @classmethod
    def create_for_user(cls, user_id: int) -> "EmailVerificationToken":
        """
        Generate a fresh verification token for ``user_id``.

        Any existing tokens for the user are deleted first so only one
        valid token can exist at a time.

        The session is flushed (but **not** committed) so the new record
        receives a primary key.  The caller is responsible for committing.

        :param user_id: Primary key of the :class:`~src.models.user.User`.
        :return: The newly created, unflushed-committed token record.
        """
        cls.query.filter_by(user_id=user_id).delete()

        record = cls(
            user_id=user_id,
            token=secrets.token_urlsafe(32),
            expires_at=datetime.utcnow() + timedelta(hours=TOKEN_TTL_HOURS),
        )
        db.session.add(record)
        db.session.flush()
        return record

    @property
    def is_expired(self) -> bool:
        """Return ``True`` if the token's TTL has elapsed."""
        return datetime.utcnow() > self.expires_at
